#!/usr/bin/env bash


#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=128GB
#SBATCH --gpus=6
##SBATCH --constraint=xeon-4116 
#SBATCH --partition=taurus
#SBATCH --time=1-2:34:56 
##SBATCH --dependency=afterok:job_id
##SBATCH --array=1-3 
#SBATCH --account=xixu
#SBATCH --mail-type=BEGIN,END,FAIL,ALL
#SBATCH --mail-user=xixu@cs.cmu.edu 
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt


bash run.sh