#!/usr/bin/env bash


#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=128GB
#SBATCH --gpus=4
#SBATCH --constraint=xeon-4116 
#SBATCH --partition=aries
#SBATCH --time=1-2:34:56
#SBATCH --account=chinmay
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cdandekar@ucsb.edu
#SBATCH --output=stdout.txt
#SBATCH --error=stderr.txt

source /mnt/taurus/data1/chinmay/sllamaEnv/bin/activate

bash run.sh